apiVersion: v1
kind: Pod
metadata:
  name: supermario-pod
  labels:
    app: supermario
spec:
  containers:
  - name: supermario-container
    image: pengbai/docker-supermario
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: "256Mi"
        cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata: 
  name: supermario-service
spec:
  type: NodePort
  selector:
    app: supermario
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30860
