pod:
  name: supermario-pod
  labels:
    app: supermario
container:
  name: supermario-container
  image: pengbai/docker-supermario
  ports:
    containerPort: 8080
  resources:
    limits:
      memory: 256Mi
      cpu: 0.5

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30860
  portName: http
  protocol: TCP
